### ISSUE TITLE
add logo

### ISSUE THREAD

**Issue by michael-ciniawsky** [static-dev/html-whitespace-parser#10]
We need a proper Logo for SugarML

Ideas/Suggestions here :)

**Comment by Scrum** [comment]
sugar and gradient color posthtml ? <img src="http://d.kuzeyekspres.com.tr/news/51197.jpg">

**Comment by michael-ciniawsky** [comment]
@GitScrum yep, thats one option, [SugarSS](https://github.com/postcss/sugarss) logo goes in that direction. I thought about maybe derivate the posthtml logo somehow, since it look a bit like a cake/donut anyways :D. Just put a little sugar on it 😛

[![SugarML](http://image.shutterstock.com/display_pic_with_logo/524620/524620,1297697879,16/stock-vector-pinc-doughnut-vector-71161843.jpg)]

The pink stuff but on the PostHTML logo
