### ISSUE TITLE
comma-separated attributes

### ISSUE THREAD

**Issue by mrmlnc** [static-dev/html-whitespace-parser#15]
## Problem

It would be great if I could separate attributes using a comma.

## Details

```jade
input(type="checkbox", checked)
```

Perhaps we should allow to use only one type of delimiter within the same group.

👍 

```jade
input(type="checkbox", checked)
```

👎 
```jade
input(type="checkbox", checked class="{{class}}")
```

**Comment by jescalan** [comment]
Why? They aren't separated by a comma in html...

**Comment by mrmlnc** [comment]
Yes you right, first need to discuss this point. Sorry.

I'm used to this functionality and do not want to lose it when I be switch from Pug to PostHTML + SugarML. Perhaps it will help people move from Jade/Pug as me.

**Comment by jescalan** [comment]
Not worth the effort and parse complexity to implement it when there is no practical advantage at all IMO. I came from jade/pug too and it was a quick and simple adjustment. I like it much better without the extra unnecessary syntax actually.

**Comment by mrmlnc** [comment]
Yes, you right. Need to make the language cleaner. I'll close this issue. 

P.S.: It's very simple to implement 👀
