### ISSUE TITLE
Access

### ISSUE THREAD

**Issue by michael-ciniawsky** [static-dev/html-whitespace-parser#8]
@voischev @awinogradov I need access to this repo, make few minor changes and publish a new package then, since the original sugarml npm package is now sadly for reshape.

#### Name

- `posthtml-sml` (favorite)
- `posthtml-sugarml`

**Comment by voischev** [comment]
sml?

**Comment by michael-ciniawsky** [comment]
`index.sml` => `.sml`should become the default extension for SugarML, like '.sss` is for SugarSS

sml => SugarMarkupLanguage

But maybe `posthtml-sugarml`is the better/clearer package name nevertheless...

**Comment by voischev** [comment]
ok

**Comment by michael-ciniawsky** [comment]
> ok 

Ok for `posthtml-sml` or `posthtml-sugarml` ? :)

The more I think about `posthtml-sugarml` the more it makes sense, though no rename would be the best at all.... 😞 . Lesson learned to not give away npm names so easily 👍

**Comment by michael-ciniawsky** [comment]
do I have access now 👀 ?

**Comment by jescalan** [comment]
Ended up renaming the extension from `sml` to `sgr` because `sml` [is already a language](https://www.wikiwand.com/en/Standard_ML) which has been registered on github, can be found by searching google, etc. You guys definitely don't need to make this change, but it might be easiest to do it before the new version is published if you want!

**Comment by michael-ciniawsky** [comment]
Then `posthtml-sugarml` is the best option to go forward for now. 

Besides that I'm still in favour discussing an eventual merging route between posthtml && reshape in the future

**Comment by jescalan** [comment]
Happy to discuss this if you want!

**Comment by voischev** [comment]
> do I have access now 👀 ?

yes)

**Comment by michael-ciniawsky** [comment]
> Happy to discuss this if you want!

@jescalan :+1:

@voischev Ok if a make an organisation wide project for that propose? We should  have an overall overview of all eventual required/intended changes in all repos :). There is also [htmlnano #32](https://github.com/maltsev/htmlnano/issues/32) and soon a similiar issue @htmllint to be aware of :). Also a single file component (like Vue Components, but -Vue ;) ) spec + plugin + eventual loader is something I would like to discuss and see whats possible with posthtml.

**component.html**

``` html
<style postcss [critical]></style>

<template id="" name="awesome"></template>

<script babel [critical]></script>
```

**index.html**

``` html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title></title>
  <style>Critical CSS from all Components</style>

  <link rel="stylesheet" href="index.css"><!-- CSS from all Components + X-->
</head>
<body>
  <component name="awesome"></component>


  <script>Critical JS from all Components</script>
  <script src="index.js" defer></script><!-- JS from all Components + X -->
</body>
</html>
```

**Comment by jescalan** [comment]
So I was also thinking about something like the component thing you posted, but then realized that this is custom element spec + shadow dom, which both already have polyfills that work pretty well, so it got pushed back a decent bit on my list. Might still be a cool experiment though!

I also have an open issue in the vue-loader to open up support for projects like reshape and posthtml, trying to get that pushed through soon.

**Comment by michael-ciniawsky** [comment]
Yeah this needs definitely futher investigation first, but pretty sure the Single File Component approach, at least in terms of workflow could be made framework agnostic, the web components specs are still in flux, when that finally settles follow the standard and fallback to webcomponents.lite.js polyfill etc.

**Comment by michael-ciniawsky** [comment]
Done [0ed0d225fe](https://github.com/posthtml/sugarml/commit/0ed0d225fe215e39f58484c8ab2bf652cb2a4c14)`posthtml-sugarml` v1.0.0-alpha
